<?php
namespace App\Facades;
use Illuminate\Support\Facades\Facade;

class dateService extends Facade {
    protected static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'dateCheck';
    }
}
