<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class DateCheckServiceProvider extends ServiceProvider
{
     public function register()
     {
//         parent::register(); // TODO: Change the autogenerated stub
         $this->app->bind('dateCheck', 'App\Services\DateCheck');
     }
}
